"""
Agricultural Advisory and Weather Classification Package.
Contains deterministic rule-based modules for rainfall classification and advisory generation.
"""

from src.advisory.rainfall_classifier import (
    classify_rainfall,
    RainfallCategory,
    InvalidRainfallError,
    PROTOTYPE_RAINFALL_THRESHOLDS,
)
from src.advisory.advisory_engine import (
    AdvisoryEngine,
    AdvisoryRule,
    AdvisoryOutput,
    AdvisorySeverity,
    ADVISORY_RULES_REGISTRY,
    generate_agricultural_advisory,
    RULE_VERSION,
)

from src.advisory.rule_engine import (
    RuleCategory,
    ComparisonOperator,
    AgriculturalRuleDefinition,
    RuleEvaluationTrace,
    RuleEngineEvaluationResult,
    DeterministicRuleEngine,
    DEFAULT_AGRICULTURAL_RULES,
    default_rule_engine,
    RULE_ENGINE_VERSION,
    RuleEngineValidationError,
)

from src.advisory.context_builder import (
    AdvisoryContextService,
    default_advisory_context_service,
    AdvisoryContextError,
    PanchayatNotFoundError,
    HierarchyMismatchError,
    ForecastNotFoundError,
    ForecastPanchayatMismatchError,
    InvalidForecastDataError,
    RuleEvaluationError,
    build_panchayat_context,
    build_forecast_context,
    build_deterministic_risk_and_recommendations,
    build_traceability_record,
    build_ai_advisory_input,
)
from backend.app.schemas.advisory_contracts import AdvisoryContext

from src.advisory.ai_service import (
    AIAdvisoryProvider,
    MockAIAdvisoryProvider,
    HttpAIAdvisoryProvider,
    AdvisoryPromptBuilder,
    AIAdvisoryService,
    default_ai_advisory_service,
    AIExecutionMetadata,
    AIAdvisoryResult,
    PROMPT_VERSION,
    AIAdvisoryServiceError,
    AIProviderConfigError,
    AIProviderTimeoutError,
    AIProviderUnavailableError,
    AIProviderAuthError,
    AIProviderRateLimitError,
    AIOutputValidationError,
    ForecastGroundednessViolationError,
    get_ai_advisory_provider,
)

__all__ = [
    "classify_rainfall",
    "RainfallCategory",
    "InvalidRainfallError",
    "PROTOTYPE_RAINFALL_THRESHOLDS",
    "AdvisoryEngine",
    "AdvisoryRule",
    "AdvisoryOutput",
    "AdvisorySeverity",
    "ADVISORY_RULES_REGISTRY",
    "generate_agricultural_advisory",
    "RULE_VERSION",
    "RuleCategory",
    "ComparisonOperator",
    "AgriculturalRuleDefinition",
    "RuleEvaluationTrace",
    "RuleEngineEvaluationResult",
    "DeterministicRuleEngine",
    "DEFAULT_AGRICULTURAL_RULES",
    "default_rule_engine",
    "RULE_ENGINE_VERSION",
    "RuleEngineValidationError",
    "AdvisoryContext",
    "AdvisoryContextService",
    "default_advisory_context_service",
    "AdvisoryContextError",
    "PanchayatNotFoundError",
    "HierarchyMismatchError",
    "ForecastNotFoundError",
    "ForecastPanchayatMismatchError",
    "InvalidForecastDataError",
    "RuleEvaluationError",
    "build_panchayat_context",
    "build_forecast_context",
    "build_deterministic_risk_and_recommendations",
    "build_traceability_record",
    "build_ai_advisory_input",
    "AIAdvisoryProvider",
    "MockAIAdvisoryProvider",
    "HttpAIAdvisoryProvider",
    "AdvisoryPromptBuilder",
    "AIAdvisoryService",
    "default_ai_advisory_service",
    "AIExecutionMetadata",
    "AIAdvisoryResult",
    "PROMPT_VERSION",
    "AIAdvisoryServiceError",
    "AIProviderConfigError",
    "AIProviderTimeoutError",
    "AIProviderUnavailableError",
    "AIProviderAuthError",
    "AIProviderRateLimitError",
    "AIOutputValidationError",
    "ForecastGroundednessViolationError",
    "get_ai_advisory_provider",
]
