-- =============================================================================
-- Migration: Add Officer Review, Versioning, Concurrency, and Audit Trail
-- Version: 20260929000001
-- Phase: 5.6
-- Description:
--   1. Adds versioning, optimistic locking, and content tracking columns to advisories:
--      - version: INTEGER DEFAULT 1 NOT NULL (optimistic concurrency counter)
--      - advisory_source: TEXT DEFAULT 'DETERMINISTIC_RULES' (e.g. AI_AUGMENTED, DETERMINISTIC_FALLBACK, OFFICER_AMENDED)
--      - validation_status: TEXT DEFAULT 'VALIDATED' (VALIDATED, FAILED_VALIDATION, PENDING)
--      - validation_report: JSONB (stores safety violations / checks summary)
--      - original_content: JSONB (preserves original generated title, text, severity)
--      - edited_content: JSONB (preserves latest officer edits and rationale)
--      - approved_content: JSONB (preserves final approved wording and parameters)
--      - rejection_reason: TEXT (explicit justification for rejection)
--      - updated_at: TIMESTAMPTZ DEFAULT NOW()
--   2. Creates advisory_audit_logs table to record immutable event provenance:
--      - (advisory_id, action, officer_id, previous_status, new_status, version, reason, details, created_at)
--   3. Adds performance and audit indexing.
-- Safety Invariant:
--   ZERO drops, ZERO truncates, ZERO deletions. 100% additive and backwards-compatible.
-- =============================================================================

-- 1. Extend advisories table with versioning and lifecycle tracking columns
ALTER TABLE advisories ADD COLUMN IF NOT EXISTS version INTEGER DEFAULT 1 NOT NULL;
ALTER TABLE advisories ADD COLUMN IF NOT EXISTS advisory_source TEXT DEFAULT 'DETERMINISTIC_RULES';
ALTER TABLE advisories ADD COLUMN IF NOT EXISTS validation_status TEXT DEFAULT 'VALIDATED';
ALTER TABLE advisories ADD COLUMN IF NOT EXISTS validation_report JSONB;
ALTER TABLE advisories ADD COLUMN IF NOT EXISTS original_content JSONB;
ALTER TABLE advisories ADD COLUMN IF NOT EXISTS edited_content JSONB;
ALTER TABLE advisories ADD COLUMN IF NOT EXISTS approved_content JSONB;
ALTER TABLE advisories ADD COLUMN IF NOT EXISTS rejection_reason TEXT;
ALTER TABLE advisories ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- 2. Create advisory_audit_logs table
CREATE TABLE IF NOT EXISTS advisory_audit_logs (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    advisory_id BIGINT NOT NULL REFERENCES advisories(id) ON DELETE CASCADE,
    action TEXT NOT NULL,
    officer_id TEXT,
    previous_status TEXT,
    new_status TEXT,
    version INTEGER DEFAULT 1 NOT NULL,
    reason TEXT,
    details JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- 3. Performance and Audit Indexes
CREATE INDEX IF NOT EXISTS idx_advisories_version ON advisories (version);
CREATE INDEX IF NOT EXISTS idx_advisories_validation_status ON advisories (validation_status);
CREATE INDEX IF NOT EXISTS idx_advisory_audit_logs_advisory_id ON advisory_audit_logs (advisory_id);
CREATE INDEX IF NOT EXISTS idx_advisory_audit_logs_action ON advisory_audit_logs (action);
CREATE INDEX IF NOT EXISTS idx_advisory_audit_logs_created_at ON advisory_audit_logs (created_at);

-- Comments
COMMENT ON TABLE advisory_audit_logs IS 'Immutable chronological audit trail of all automated and officer actions on advisories.';
COMMENT ON COLUMN advisory_audit_logs.action IS 'Action type: GENERATED, VALIDATED, REVIEWED, EDITED, APPROVED, REJECTED, PUBLISHED.';
COMMENT ON COLUMN advisory_audit_logs.version IS 'Advisory version number at the time of the action.';
COMMENT ON COLUMN advisories.version IS 'Optimistic locking integer, incremented on every content or status change.';
COMMENT ON COLUMN advisories.original_content IS 'Snapshot of the original generated/validated advisory before officer edits.';
COMMENT ON COLUMN advisories.edited_content IS 'Snapshot of officer-edited advisory content.';
COMMENT ON COLUMN advisories.approved_content IS 'Snapshot of the approved advisory content released to farmers.';
