-- =============================================================================
-- Migration: Multi-District Scalable Weather Architecture
-- Timestamp: 2026-09-25
-- Description: Creates normalized administrative hierarchy (districts, blocks,
--              panchayats), station_metadata, block_forecasts, and
--              weather_observations tables with performance indexes and RLS.
-- Safety Invariant: NEVER drops or alters existing panchayat_weather_data,
--                   downscaled_forecasts, or advisories tables.
-- =============================================================================

-- 1. Districts table
CREATE TABLE IF NOT EXISTS districts (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT UNIQUE NOT NULL,
    state TEXT NOT NULL DEFAULT 'Maharashtra',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Blocks table (Administrative Tehsils / Talukas)
CREATE TABLE IF NOT EXISTS blocks (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    district_id BIGINT REFERENCES districts(id) ON DELETE RESTRICT,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT uq_blocks_district_name UNIQUE (district_id, name)
);

-- 3. Panchayats table (Village Panchayats)
CREATE TABLE IF NOT EXISTS panchayats (
    id BIGINT PRIMARY KEY,
    lgd_code BIGINT NOT NULL,
    panchayat_code TEXT,
    name TEXT NOT NULL,
    block_id BIGINT REFERENCES blocks(id) ON DELETE RESTRICT,
    district_id BIGINT REFERENCES districts(id) ON DELETE RESTRICT,
    latitude NUMERIC,
    longitude NUMERIC,
    elevation_m NUMERIC,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT uq_panchayats_id UNIQUE (id)
);

-- 4. Station Metadata table (AWS / ARG Weather Stations)
CREATE TABLE IF NOT EXISTS station_metadata (
    station_id TEXT PRIMARY KEY,
    station_name TEXT,
    latitude NUMERIC,
    longitude NUMERIC,
    district_name TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Block Forecasts table (Regional NWP Precipitation Forecasts)
CREATE TABLE IF NOT EXISTS block_forecasts (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    district_id BIGINT REFERENCES districts(id),
    block_id BIGINT REFERENCES blocks(id),
    district_name TEXT NOT NULL,
    block_name TEXT NOT NULL,
    forecast_issue_date DATE NOT NULL,
    forecast_date DATE NOT NULL,
    rainfall_mm NUMERIC NOT NULL,
    source TEXT DEFAULT 'IMD',
    source_model TEXT DEFAULT 'GFS',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    CONSTRAINT uq_block_forecasts UNIQUE (
        district_name,
        block_name,
        forecast_issue_date,
        forecast_date,
        source_model
    )
);

-- 6. Weather Observations table (Panchayat Ground Observations)
CREATE TABLE IF NOT EXISTS weather_observations (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    panchayat_id BIGINT NOT NULL,
    lgd_code BIGINT NOT NULL,
    station_id TEXT,
    observation_date DATE NOT NULL,
    actual_rainfall_mm NUMERIC,
    station_distance_km NUMERIC,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    CONSTRAINT uq_weather_observations UNIQUE (panchayat_id, observation_date)
);

-- =============================================================================
-- PERFORMANCE INDEXES
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_districts_name ON districts (name);
CREATE INDEX IF NOT EXISTS idx_blocks_district_id ON blocks (district_id);
CREATE INDEX IF NOT EXISTS idx_blocks_name ON blocks (name);

CREATE INDEX IF NOT EXISTS idx_panchayats_district_id ON panchayats (district_id);
CREATE INDEX IF NOT EXISTS idx_panchayats_block_id ON panchayats (block_id);
CREATE INDEX IF NOT EXISTS idx_panchayats_lgd_code ON panchayats (lgd_code);
CREATE INDEX IF NOT EXISTS idx_panchayats_name ON panchayats (name);

CREATE INDEX IF NOT EXISTS idx_block_forecasts_district_block ON block_forecasts (district_name, block_name);
CREATE INDEX IF NOT EXISTS idx_block_forecasts_forecast_date ON block_forecasts (forecast_date);
CREATE INDEX IF NOT EXISTS idx_block_forecasts_forecast_issue_date ON block_forecasts (forecast_issue_date);

CREATE INDEX IF NOT EXISTS idx_weather_observations_panchayat_id ON weather_observations (panchayat_id);
CREATE INDEX IF NOT EXISTS idx_weather_observations_observation_date ON weather_observations (observation_date);
CREATE INDEX IF NOT EXISTS idx_weather_observations_station_id ON weather_observations (station_id);
CREATE INDEX IF NOT EXISTS idx_weather_obs_panchayat_date ON weather_observations (panchayat_id, observation_date);

-- =============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- =============================================================================

ALTER TABLE districts ENABLE ROW LEVEL SECURITY;
ALTER TABLE blocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE panchayats ENABLE ROW LEVEL SECURITY;
ALTER TABLE station_metadata ENABLE ROW LEVEL SECURITY;
ALTER TABLE block_forecasts ENABLE ROW LEVEL SECURITY;
ALTER TABLE weather_observations ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public read districts') THEN
        CREATE POLICY "Public read districts" ON districts FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public read blocks') THEN
        CREATE POLICY "Public read blocks" ON blocks FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public read panchayats') THEN
        CREATE POLICY "Public read panchayats" ON panchayats FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public read station_metadata') THEN
        CREATE POLICY "Public read station_metadata" ON station_metadata FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public read block_forecasts') THEN
        CREATE POLICY "Public read block_forecasts" ON block_forecasts FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public read weather_observations') THEN
        CREATE POLICY "Public read weather_observations" ON weather_observations FOR SELECT USING (true);
    END IF;
END $$;
