-- =============================================================================
-- Migration: Farmer Personalization & Preferences Layer (Phase 6.3)
-- Timestamp: 2026-09-29
-- Description: Creates farmer_preferences table storing preferred Panchayat ID,
--              preferred language, and updated timestamp.
-- Safety Invariant: ZERO destructive changes, ZERO table rewrites.
--                   100% additive and strictly linked to existing panchayats.
-- =============================================================================

CREATE TABLE IF NOT EXISTS farmer_preferences (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    farmer_id TEXT UNIQUE NOT NULL,
    panchayat_id BIGINT NOT NULL REFERENCES panchayats(id) ON DELETE CASCADE,
    preferred_language VARCHAR(10) NOT NULL DEFAULT 'en',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- B-tree indexes for fast farmer lookup and Panchayat reverse lookup
CREATE INDEX IF NOT EXISTS idx_farmer_preferences_farmer_id ON farmer_preferences(farmer_id);
CREATE INDEX IF NOT EXISTS idx_farmer_preferences_panchayat_id ON farmer_preferences(panchayat_id);

-- Enable Row-Level Security
ALTER TABLE farmer_preferences ENABLE ROW LEVEL SECURITY;

-- Permissive policies for application access
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'farmer_preferences' AND policyname = 'Allow public read access to farmer_preferences'
    ) THEN
        CREATE POLICY "Allow public read access to farmer_preferences"
            ON farmer_preferences FOR SELECT
            USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'farmer_preferences' AND policyname = 'Allow authenticated insert/update to farmer_preferences'
    ) THEN
        CREATE POLICY "Allow authenticated insert/update to farmer_preferences"
            ON farmer_preferences FOR ALL
            USING (true)
            WITH CHECK (true);
    END IF;
END $$;
