-- =============================================================================
-- Migration: Panchayat Boundary Spatial Foundation (Phase 6.1)
-- Timestamp: 2026-09-29
-- Description: Enables PostGIS extension safely and provisions the normalized
--              panchayat_boundaries table for point-in-polygon resolution.
--              Boundary geometry is decoupled from normal panchayat metadata.
-- Safety Invariant: ZERO table rewrites, ZERO destructive alterations.
--                   100% additive and compatible with District -> Block -> Panchayat.
-- =============================================================================

-- 1. Ensure PostGIS spatial extension is enabled
CREATE EXTENSION IF NOT EXISTS postgis;

-- 2. Dedicated Panchayat boundaries table
CREATE TABLE IF NOT EXISTS panchayat_boundaries (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    panchayat_id BIGINT UNIQUE NOT NULL REFERENCES panchayats(id) ON DELETE CASCADE,
    boundary GEOMETRY(Geometry, 4326) NOT NULL,
    source TEXT NOT NULL DEFAULT 'AUTHORITATIVE_LGD',
    simplified_boundary GEOMETRY(Geometry, 4326),
    properties JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT chk_boundary_type CHECK (
        ST_GeometryType(boundary) IN ('ST_Polygon', 'ST_MultiPolygon')
    )
);

-- 3. High-performance Spatial GiST Index on boundary geometry
CREATE INDEX IF NOT EXISTS idx_panchayat_boundaries_geom 
    ON panchayat_boundaries USING GIST (boundary);

-- 4. Foreign key index linking back to authoritative panchayats table
CREATE INDEX IF NOT EXISTS idx_panchayat_boundaries_panchayat_id 
    ON panchayat_boundaries (panchayat_id);

-- 5. Row Level Security (RLS)
ALTER TABLE panchayat_boundaries ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public read panchayat_boundaries') THEN
        CREATE POLICY "Public read panchayat_boundaries" ON panchayat_boundaries FOR SELECT USING (true);
    END IF;
END $$;
