-- =============================================================================
-- Migration: Panchayat-Based Location Alerts & Notifications (Phase 6.2)
-- Timestamp: 2026-09-29
-- Description: Creates farmer_devices, notification_events, and
--              notification_deliveries tables with uniqueness constraints,
--              idempotency keys, and RLS policies.
-- Safety Invariant: ZERO destructive changes, ZERO table rewrites.
--                   100% additive and strictly linked to existing panchayats & advisories.
-- =============================================================================

-- 1. Farmer Device Tokens (strictly linked to authoritative panchayats)
CREATE TABLE IF NOT EXISTS farmer_devices (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    device_token TEXT UNIQUE NOT NULL,
    panchayat_id BIGINT NOT NULL REFERENCES panchayats(id) ON DELETE CASCADE,
    device_platform TEXT DEFAULT 'android',
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Notification Events (Alert events derived from approved advisories)
CREATE TABLE IF NOT EXISTS notification_events (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    idempotency_key TEXT UNIQUE NOT NULL,
    advisory_id BIGINT NOT NULL REFERENCES advisories(id) ON DELETE CASCADE,
    advisory_version INTEGER NOT NULL,
    panchayat_id BIGINT NOT NULL REFERENCES panchayats(id) ON DELETE CASCADE,
    forecast_id BIGINT,
    alert_category TEXT NOT NULL,
    severity TEXT NOT NULL,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'PENDING',
    target_count INTEGER DEFAULT 0,
    success_count INTEGER DEFAULT 0,
    failure_count INTEGER DEFAULT 0,
    published_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Notification Deliveries (Individual device delivery attempts & retries)
CREATE TABLE IF NOT EXISTS notification_deliveries (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_id BIGINT NOT NULL REFERENCES notification_events(id) ON DELETE CASCADE,
    target_device_id BIGINT NOT NULL REFERENCES farmer_devices(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'PENDING',
    attempt_count INTEGER DEFAULT 1,
    last_attempted_at TIMESTAMPTZ DEFAULT NOW(),
    error_message TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT uq_notification_delivery_event_target UNIQUE (event_id, target_device_id)
);

-- Indexes for high-throughput querying & idempotency
CREATE INDEX IF NOT EXISTS idx_farmer_devices_panchayat_id ON farmer_devices (panchayat_id);
CREATE INDEX IF NOT EXISTS idx_farmer_devices_token ON farmer_devices (device_token);
CREATE INDEX IF NOT EXISTS idx_notification_events_idempotency_key ON notification_events (idempotency_key);
CREATE INDEX IF NOT EXISTS idx_notification_events_panchayat_id ON notification_events (panchayat_id);
CREATE INDEX IF NOT EXISTS idx_notification_events_advisory_id ON notification_events (advisory_id);
CREATE INDEX IF NOT EXISTS idx_notification_events_status ON notification_events (status);
CREATE INDEX IF NOT EXISTS idx_notification_deliveries_event_id ON notification_deliveries (event_id);
CREATE INDEX IF NOT EXISTS idx_notification_deliveries_status ON notification_deliveries (status);

-- Row Level Security (RLS)
ALTER TABLE farmer_devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification_deliveries ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public read farmer_devices') THEN
        CREATE POLICY "Public read farmer_devices" ON farmer_devices FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public insert update farmer_devices') THEN
        CREATE POLICY "Public insert update farmer_devices" ON farmer_devices FOR ALL USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public read notification_events') THEN
        CREATE POLICY "Public read notification_events" ON notification_events FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public read notification_deliveries') THEN
        CREATE POLICY "Public read notification_deliveries" ON notification_deliveries FOR SELECT USING (true);
    END IF;
END $$;
